#!/bin/sh

# script/init: Initializes a new project

set -e

cd "$(dirname "$0")/.."

docker volume inspect dreadlabs_composer-cache 1>/dev/null 2>&1 || {
    docker volume create dreadlabs_composer-cache;
}

if [ ! -f composer.json ]; then
    docker run \
        --interactive \
        --tty \
        --rm \
        --volume dreadlabs_composer-cache:/var/cache/composer \
        --volume "$(pwd)":/app \
        --workdir /app \
        --entrypoint /usr/local/bin/entrypoint-suexec.sh \
        dreadlabs/php-lib:7.0-dev composer init

    mkdir -p src/ tests/
    touch phpunit.xml.dist
else
    echo "==> Project already initialized."
    exit 1
fi
